### ISSUE TITLE
Authenticated user should change after completing SSO authentication with another user

### ISSUE THREAD

**Issue by joonashak** [joonashak/nestjs-clone-bay#16]
Repro:

1. Start with no users in database.
2. SSO as user 1.
3. Clear cookies.
4. SSO as user 2.
5. SSO again as user 1. Note that the session is not changed and active user is still user 2.

This could be an actual issue when carelessly using shared computers. Probably more of an annoyance in development and testing. Should be fixed anyway.

### TODO:

- [ ] If user is logged in before SSO, check if the character returned from SSO is registered under another user.
- [ ] Handle existing session:
  - [ ] Invalidate current session. (Access tokens cannot be revoked via SSO API and refresh tokens are not shared, so no point in revoking tokens here.)
  - [ ] Log the attempt.
  - [ ] Authenticate the new user.
