### ISSUE TITLE
User mocking

### ISSUE THREAD

**Issue by joonashak** [joonashak/nestjs-clone-bay#18]
E2E testing is currently pretty challenging if authentication is required as that necessitates mocking an SSO server. Even after that is done, setting roles, etc. is not trivial. This applies especially for client software using this library.

Opinions differ on whether clients should mock the whole SSO flow. However, I feel that in practice that would be rather hard which could result in less testing making the situation even worse. Therefore user mocking is introduced at library level as a development tool.

## TODO

- [x] Conditionally imported mocking module.
- [x] Method to create mock users.
- [x] Method to login as mock user.
- [x] Controller for using mocking via HTTP.
- [x] Export module for using mocking via code.
- [x] Docs.
- [x] Tests.
