### ISSUE TITLE
Create new user when authenticating for the first time

### ISSUE THREAD

**Issue by joonashak** [joonashak/nestjs-clone-bay#6]
Develop in conjuction with #8 

### TODO:

- [x] User model and service.
- [x] Character model changes:
  - [x] Get corp and alliance from ESI on create.
- [x] Create user if it does not exist:
  - [x] Option to disable new user registrations.
  - [x] Respect allowlists.
