### ISSUE TITLE
Option to restrict authentication by character, corporation or alliance

### ISSUE THREAD

**Issue by joonashak** [joonashak/nestjs-clone-bay#8]
### TODO:

- [x] Authentication should be allowed when user matches any filter.
  - [x] Check when logging in through SSO.
  - [x] Check in authentication guards protecting consumer app endpoints (already logged in users).
  - [x] Empty filter disables the respective check.
- [x] Add option to apply this allowlist only to new user registration (i.e., existing users are allowed to log in).
- [x] _Need to get character data from ESI to see corp and alliance membership._
