### ISSUE TITLE
Expose service to configure lib behavior during run-time

### ISSUE THREAD

**Issue by joonashak** [joonashak/nestjs-clone-bay#9]
Settings for development:

- [ ] ~Disable authentication switch.~
- [x] Allowlists for authentication filtering by character, corporation and alliance.

### TODO:

- [x] Entity and service for dynamic configuration.
- [x] Lifecycle methods to ensure exactly one configuration is persisted.
- [x] Docs.
- [x] Nice API for client: `CloneBayConfigService`?
- [x] Cache getter because this is used all the time.
